
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gitnpdgfqzovzvivscme.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdpdG5wZGdmcXpvdnp2aXZzY21lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NjgwODcsImV4cCI6MjA1OTM0NDA4N30._YLUYQz30ffm2FODsE5hz4YezbVxYI-xJLjnblSkCRQ";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
